### ISSUE TITLE
Falta index.html con estructura básica

### ISSUE THREAD

**Issue by juanmait** [marcelovidal/maquetacion#1]
Hola @marcelovidal. Te faltaría agregar un archivo `index.html` con una estructura básica. Una pabada, pero aprobeché para crear un *issue*, que es la forma en la que los devs reportan faltantes y cosas así. Una vez que el *issue* está resuelto, el desarrollador *dueño* del repo lo puede cerrar.

Saludos!

**Comment by marcelovidal** [comment]
Buenisimo, allí lo agregue.

**Comment by marcelovidal** [comment]
Allí hice las actualizaciones del index y de style @juanmait .
